# Generated by Django 4.1.2 on 2022-10-31 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('audio_video', models.FileField(blank=True, null=True, upload_to='media/audio_video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'mov', 'avi', 'wav', 'mp3', 'aac', 'flac'])])),
                ('text', models.FileField(blank=True, null=True, upload_to='media/text/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['itx', 'txt', 'tex', 'md'])])),
            ],
        ),
    ]
