# Generated by Django 4.1.2 on 2022-11-01 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='audio_video',
            field=models.FileField(blank=True, null=True, upload_to='media/audio_video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'mov', 'avi', 'wav', 'mp3', 'aac', 'flac', 'pdf'])]),
        ),
    ]
